### ISSUE TITLE
failing tests due to hardcoded year in expected results

### ISSUE THREAD

**Issue by Trott** [COVID19Tracking/website#1889] opened 2022-01-12 18:49 UTC
Tests are failing because [the year is hardcoded into the expected results](https://github.com/COVID19Tracking/website/blob/bdee11f90f18cedc1732e10927a5ff585bffec85/src/__tests__/components/layout/__snapshots__/footer.js.snap#L132).

This seems to be a `jest` thing and I don't know if it's supposed to get automatically updated or if there's a way to make that particular part of the results more forgiving so that you don't have to update it every year, or what, but taking a moment to log the issue. Thanks.

**Comment by Trott** [comment] 2022-01-12 18:49
> This seems to be a `jest` thing

Ref: https://jestjs.io/docs/snapshot-testing

**Comment by Emeka-Ugbanu-hub** [comment] 2022-01-29 23:17
I would love to help with this

**Comment by kevee** [comment] 2022-02-08 16:02
Thanks, @Trott for the catch. The issue is that a Jest snapshot that should have been updated daily wasn't being run because of the shutdown of some of our Github actions. I've manually bumped the snapshots in #1894. This issue will be closed when the PR is merged.

**Closed** 2022-02-08 18:09 UTC
Labels: bug
