### ISSUE TITLE
CDC and project data bar charts need the same X axis

### ISSUE THREAD

**Issue by jeremiak** [COVID19Tracking/website#530] opened 2020-04-14 17:13 UTC
The first bar chart compares CDC data to our project's data. In order to be more comparable, they need to have the same X axis so that a reader can easily scan the difference.

<img width="1111" alt="Screen Shot 2020-04-14 at 1 13 17 PM" src="https://user-images.githubusercontent.com/780941/79253870-e523c980-7e51-11ea-958e-6f7b14e6c6e9.png">

**Comment by vijaysharwar** [comment] 2020-04-14 17:42
I can take a look at this, but it may not be easy. I don't think D3 gives precise control over the ticks (by design, to allow scaling and dependency on the data). I suspect we're seeing different ticks because the data for these two charts is different.

**Comment by jeremiak** [comment] 2020-04-14 17:47
Yup, agreed on your root cause analysis @vijaysharwar! One way we've done this before is to add props called like `yExtent`, which is an array that is used for the `.domain` of the Y scale. Maybe we should do a similar set of props for the X axis?

**Comment by vijaysharwar** [comment] 2020-04-14 18:18
@jeremiak using `extent` won't work, because of the way [scaleBand](https://github.com/d3/d3-scale#scaleBand) operates. I think we need to normalize the two data sets before sending to `BarChart`. Here're the current data ranges:

- CDC: January 18 - April 8
- Ours: Feb 28 - April 13

So programmatically speaking, I think we need to find the earliest and latest dates from the two sets, and apply those to both data arrays...

**Comment by jeremiak** [comment] 2020-04-14 18:19
Makes sense to me as a good approach @vijaysharwar!

**Comment by vijaysharwar** [comment] 2020-04-14 18:26
Or we could switch to `scaleTime` instead of `scaleBand` in `BarChart`. So far, all three instances of `BarChart` have dates on the x-axis. But this would obviously restrict how we can use that component.

**Comment by vijaysharwar** [comment] 2020-04-14 18:31
Yeah, @jeremiak I think we need to switch to `scaleTime`. Because `scaleBand` doesn't automatically extrapolate missing items. I think it just outputs 1:1, so we'd need the two data sets to contain the precise number of items with equivalent date values.

**Comment by AaronMullan** [comment] 2020-04-14 21:01
Dang I was just working on this and forgot to add a comment.  I'll put in a PR in case you guys like the solution I came up with.

**Comment by AaronMullan** [comment] 2020-04-14 21:05
PR  #549

**Comment by vijaysharwar** [comment] 2020-04-14 21:12
@AaronMullan ack, sorry to be overlapping. I commented in #549, but I have a different approach that normalizes the two data arrays. I think it'll be more future proof, but definitely adds complexity. cc @goleary @jeremiak

**Comment by vijaysharwar** [comment] 2020-04-15 01:27
@julialedur this is resolved via #552, can close this Issue.

**Closed** 2020-04-15 01:37 UTC
Labels: Visualization 📈
