### ISSUE TITLE
Aria active not appearing for parents of subpages

### ISSUE THREAD

**Issue by schwartzadev** [COVID19Tracking/website#345] opened 2020-04-02 03:20 UTC
From @beep in #276 :
> I might be misreading the site hierarchy, but I think the active navigation state seems to be getting lost on a few “sub” pages. (For example, click on “FAQs for Newsrooms”, and it’s active; click over to “About the project”, and the bar’s removed from the “FAQs for Newsrooms” link.)

This still seems to be the case: if you browse to a subpage that is not that subpage's index, the parent is no longer underlined:

```
|- About the Data*
  |- About the Data
  |- Data API
  |- Software & Thanks
```
(I added the `*` for clarity.)

In this case, `About the Data*` is the parent. `About the Data` (the subpage) has no problems; the `About the Data*` parent is underlined. I believe this is because this subpage is the index for this parent. The `Data API` and `Software & Thanks` pages should have the underlined parent yet do not, presumably because they are not the index of the parent.

Beautifully annotated photos :sparkles: for reference:
![image](https://user-images.githubusercontent.com/18607205/78207256-65aff680-745e-11ea-9533-2927e68b34ca.png)
![image](https://user-images.githubusercontent.com/18607205/78207285-7ceee400-745e-11ea-8531-b42a2d054609.png)

**Comment by kevee** [comment] 2020-04-03 11:44
Hm, there's no explicit relationship between the header nav and the sub nav, and in the case of "Get the data" and "Data API" they are both in the same nav, so when I made a quick test to apply aria-current=true to any page that's the top-level item of a sub navigation, I got:

![image](https://user-images.githubusercontent.com/270536/78357189-fed62e80-757e-11ea-955e-f3b47cccde26.png)

**Comment by beep** [comment] 2020-04-03 13:37
> there's no explicit relationship between the header nav and the sub nav

Oh innnnnteresting. Is there a way for us to create that relationship? Seems we’d want to be able to signal which top-level section “owns” the page the user’s viewing.

> and in the case of "Get the data" and "Data API" they are both in the same nav

Ah, great catch—I’d totally missed that. That might be an IA question, if not a bug: if “Data API” is on the top level, do we need it `underneath` “Get the Data”? (I’d personally be fine keeping it just up top, but there might be some context here I’m missing!)

**Comment by kevee** [comment] 2020-04-03 13:42
There was a request to add it to the top for now. I think long-term (for this project, 3-5 days) there is content/IA work that is going to be coming down the pike.

**Comment by beep** [comment] 2020-04-03 13:51
Yeah, sorry: I think it makes sense up top! But it seems like a top-level nav item shouldn’t _also_ live on the subnav.

(I guess I’m not clear on how the navigation’s constructed, which might help with some of these questions.)

**Comment by kevee** [comment] 2020-04-03 13:56
Main nav is [in a YAML file](https://covid19tracking.github.io/website-docs/?path=/docs/main-navigation--page) - mostly because there's design implications, but really because it was built before Contentful was a thing and we just didn't have time.

[Sub Nav is in Contentful](https://covid19tracking.github.io/website-docs/?path=/docs/using-contentful--page#navigation-groups)

**Comment by kevee** [comment] 2020-04-10 18:12
Closing for now, there's IA changes coming down the pike, and #412 fixed some of this.

**Closed by kevee** 2020-04-10 18:12 UTC
Labels: bug
