### ISSUE TITLE
Implement "Data Visualizations" page (website restructure)

### ISSUE THREAD

**Issue by lucasgonze** [COVID19Tracking/website#172] opened 2020-03-25 00:11 UTC
Requirements:
https://docs.google.com/document/d/1NPypuNap-yFaOpzd2SKkXbI9GnkzI5QOsozLACSBuww/edit#bookmark=id.855uixcuskiw

**Comment by artyomtrityak** [comment] 2020-03-25 16:55
Anyone is working on data visualizations? I want to help and build some using d3.js

**Comment by jonah** [comment] 2020-03-26 03:17
I'm building some visualizations on my own, pulling data from the api.  I'm a php developer so I'm not going to burden this project with my limited node.js skills:)  Not sure if its helpful to this project, but maybe food for thought:

https://corona.worldinfoshare.com

I'm using google charts.  My interest is in showing trends and rates, and eventually adding in confirmed cases per capita, cases per hospital bed capacity, etc.  I'd also like to add data for closing/opening of public schools, and start/stop dates of shelter in place orders to try to gauge the impact of public policy on the spread rates.

**Comment by writenorman** [comment] 2020-03-26 18:39
Same here.. hoping to contribute to data visualization, have experience with Javascript node.js and jQuery.  Mocked up a static prototype in excel to compare US state by state.  Would be nice to make it interactive and polling live data.
![image](https://user-images.githubusercontent.com/58993339/77683797-55d07800-6f6f-11ea-9c70-7d6174d69567.png)

**Comment by roy7** [comment] 2020-03-28 16:42
@writenorman If you make that chart in Google Charts, it can pull data directly from the Google Sheet so it'll update live.

I'd like suggest someone add state population to the sheet someplace, to make per capita graphing easier.

**Comment by kissane** [comment] 2020-03-29 23:26
Hi everyone! We have a massive data visualization site section coming out within a day or two, and then it will be much clearer how to contribute there! Thanks for being here—we're spinning this piece up ASAP.

**Comment by kevee** [comment] 2020-04-02 15:26
Dupe of #91, closing.

**Closed by kevee** 2020-04-02 15:26 UTC
